Repository innosat-mats/rac-extract-payload, pull requests merged in 2020-05, with the labels that each got.

#73 CCD metadata as CSV Output
  internal/aez/ccd_data.go
  internal/aez/ccd_data_test.go
  internal/aez/ccd_image.go
  internal/aez/ccd_image_test.go
  internal/aez/general.go
  internal/common/callback.go
  internal/common/datarecord.go
  internal/common/datarecord_test.go
  internal/common/exportable.go
  internal/exports/disk_writer.go
  internal/exports/stdout_writer.go
  internal/extractors/extract_data_test.go
Labels: question

#111 Only release notes configuration
  release-notes.yml
Labels: system

#112 Wrong place and name for the configuration file
  .github/release-drafter.yml
Labels: system

#109 Access data from command line
  README.md
Labels: documentation

#113 Inhibit compiler warnings
  internal/decodejpeg/decode.go
Labels: system

#110 Automating releases better
  .github/release-drafter.yml
  .github/workflows/go.yml
  .github/workflows/release.yml
Labels: system

#116 Issue 105 race conditions
  Makefile
  internal/exports/aws_s3_writer.go
  internal/extractors/extract_data.go
Labels: bug

#117 nanosec fix
  internal/ccsds/cuc.go
Labels: chore
